_format_version: "3.0"
_transform: true

services:
  # Vendor FastAPI Application (Primary API Gateway)
  - name: vendor-fastapi-api
    url: http://host.docker.internal:8080
    routes:
      - name: vendor-fastapi-route
        paths:
          - /v1/api
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
          headers: [Accept, Authorization, Content-Type, X-API-Key, X-Request-ID]
          credentials: true
          max_age: 3600
      - name: rate-limiting
        config:
          minute: 200
          hour: 2000
          policy: local
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Kong-Proxy: true"
              - "X-Service: vendor-fastapi"

  # GraphQL API Gateway
  - name: graphql-api-gateway
    url: http://host.docker.internal:4000/graphql
    routes:
      - name: graphql-route
        paths:
          - /graphql
        strip_path: false
        methods:
          - GET
          - POST
          - OPTIONS
    plugins:
      - name: cors
      - name: rate-limiting
        config:
          minute: 150
          policy: local

  # Cursor API Gateway (Legacy)
  - name: cursor-api-gateway
    url: http://host.docker.internal:3000
    routes:
      - name: cursor-api-route
        paths:
          - /api/v1
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE
    plugins:
      - name: cors
        config:
          origins:
            - "{{ .grafana_url }}"
            - "http://localhost:3001"
            - "http://localhost:8080"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
          headers:
            - Accept
            - Authorization
            - Content-Type
            - "X-Cursor-Request"

  # Temporal Workflow Gateway
  - name: temporal-gateway
    url: http://temporal-dev:7233
    routes:
      - name: temporal-api-route
        paths:
          - /temporal
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE

  # MLflow Tracking Server
  - name: mlflow-gateway
    url: http://host.docker.internal:5000
    routes:
      - name: mlflow-api-route
        paths:
          - /mlflow
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
    plugins:
      - name: cors
      - name: rate-limiting
        config:
          minute: 100
          policy: local

  # LiteLLM Proxy Gateway
  - name: litellm-gateway
    url: http://host.docker.internal:4000
    routes:
      - name: litellm-api-route
        paths:
          - /llm
        strip_path: true
        methods:
          - GET
          - POST
    plugins:
      - name: cors
      - name: rate-limiting
        config:
          minute: 60
          policy: local
      - name: key-auth
        config:
          key_names:
            - "X-API-Key"
            - "Authorization"

  # DataHub Metadata Gateway
  - name: datahub-gateway
    url: http://datahub-gms:8080
    routes:
      - name: datahub-api-route
        paths:
          - /datahub
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE

  # Redis Cache Gateway (for admin)
  - name: redis-gateway
    url: http://host.docker.internal:6379
    routes:
      - name: redis-admin-route
        paths:
          - /redis
        strip_path: true
        methods:
          - GET
          - POST
    plugins:
      - name: ip-restriction
        config:
          allow:
            - 127.0.0.1
            - 192.168.0.0/16
            - 10.0.0.0/8

  # Neo4j Knowledge Graph Gateway
  - name: neo4j-gateway
    url: http://neo4j-dev:7474
    routes:
      - name: neo4j-api-route
        paths:
          - /neo4j
        strip_path: true
        methods:
          - GET
          - POST
    plugins:
      - name: cors
      - name: rate-limiting
        config:
          minute: 50
          policy: local

  # Qdrant Vector Database Gateway
  - name: qdrant-gateway
    url: http://host.docker.internal:6333
    routes:
      - name: qdrant-api-route
        paths:
          - /vectors
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
    plugins:
      - name: cors
      - name: rate-limiting
        config:
          minute: 100
          policy: local

  # Prometheus Metrics Gateway
  - name: prometheus-gateway
    url: http://ai-agency-prometheus:9090
    routes:
      - name: prometheus-route
        paths:
          - /metrics
        strip_path: true
        methods:
          - GET
          - POST
    plugins:
      - name: cors

  # Grafana Dashboard Gateway
  - name: grafana-gateway
    url: http://ai-agency-grafana:3000
    routes:
      - name: grafana-route
        paths:
          - /dashboard
        strip_path: true
        methods:
          - GET
          - POST

  # Ollama LLM Gateway
  - name: ollama-gateway
    url: http://host.docker.internal:11434
    routes:
      - name: ollama-api-route
        paths:
          - /ollama
        strip_path: true
        methods:
          - GET
          - POST
    plugins:
      - name: cors
      - name: rate-limiting
        config:
          minute: 30
          policy: local

  # Health Check Endpoint
  - name: health-gateway
    url: http://host.docker.internal:8080/health
    routes:
      - name: health-route
        paths:
          - /health
        strip_path: false
        methods:
          - GET

upstreams:
  - name: cursor-backend
    targets:
      - target: host.docker.internal:8080
        weight: 100
      - target: host.docker.internal:3000
        weight: 50

  - name: vendor-api-upstream
    targets:
      - target: host.docker.internal:8080
        weight: 100
    healthchecks:
      active:
        concurrency: 10
        interval: 30
        healthy:
          successes: 2
          http_statuses:
            - 200
            - 201
        unhealthy:
          http_failures: 3
          http_statuses:
            - 500
            - 502
            - 503

  - name: ml-services-upstream
    targets:
      - target: host.docker.internal:5000
        weight: 50
      - target: host.docker.internal:4000
        weight: 50
    healthchecks:
      active:
        type: http
        http_path: /health
        timeout: 10
        interval: 60

  - name: database-upstream
    targets:
      - target: host.docker.internal:5432
        weight: 100
    healthchecks:
      passive:
        healthy:
          successes: 5
        unhealthy:
          tcp_failures: 3

consumers:
  - username: cursor-admin
    tags:
      - admin
      - internal

  - username: ml-service
    custom_id: ml-service-user
    tags:
      - ml
      - internal

  - username: api-consumer
    custom_id: api-consumer-user
    tags:
      - api
      - external

plugins:
  # Global CORS configuration
  - name: cors
    config:
      origins:
        - "{{ .grafana_url }}"
        - "http://localhost:3001"
        - "http://localhost:8080"
        - "{{ .kong_url }}"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - X-API-Key
        - X-Request-ID
      credentials: true
      max_age: 3600

  # Global rate limiting
  - name: rate-limiting
    config:
      minute: 100
      hour: 5000
      policy: local
      fault_tolerant: true

  # Request/Response logging
  - name: file-log
    config:
      path: /tmp/kong-access.log
      reopen: true

  # Prometheus metrics
  - name: prometheus
    config:
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true