name: Upload Binaries to Release

on:
  release:
    types: [published]

jobs:
  upload-assets:
    name: Build & Upload Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build Binaries for Linux & Windows
        run: |
          mkdir -p build
          
          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -o build/iotamixing-linux-amd64 ./cmd/iota-mixing/
          GOOS=linux GOARCH=arm64 go build -o build/iotamixing-linux-arm64 ./cmd/iota-mixing/
          
          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -o build/iotamixing-windows-amd64.exe ./cmd/iota-mixing/
          GOOS=windows GOARCH=arm64 go build -o build/iotamixing-windows-arm64.exe ./cmd/iota-mixing/

      - name: Upload Binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            build/iotamixing-linux-amd64
            build/iotamixing-linux-arm64
            build/iotamixing-windows-amd64.exe
            build/iotamixing-windows-arm64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_IOTAMIXING_RELEASE_TOKEN }}
