# Docker Infrastructure Setup - Vendor Compliant
# Replaces containerization-setup.sh with Docker Desktop CLI and vendor tools

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ai_agency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: process.env.TIMEOUT || 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: process.env.TIMEOUT || 5s
      retries: 5

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.15-community
    environment:
      NEO4J_AUTH: neo4j/neo4j_secure_password_2025
      NEO4J_PLUGINS: '["graph-data-science"]'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo4j_secure_password_2025", "MATCH () RETURN count(*) limit 1"]
      interval: 30s
      timeout: process.env.TIMEOUT || 10s
      retries: 5

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${process.env.HOST || "localhost"}:6333/health"]
      interval: 30s
      timeout: process.env.TIMEOUT || 10s
      retries: 5

  # Ollama AI Models
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=172.17.0.8
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: process.env.TIMEOUT || 10s
      retries: 3

  # API Gateway (Kong) - Using in-memory mode for simplicity
  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: off
      KONG_ADMIN_LISTEN: 172.17.0.8:8001
      KONG_ADMIN_GUI_LISTEN: 172.17.0.8:8002
      KONG_PROXY_LISTEN: 172.17.0.8:8000, 172.17.0.8:8443 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: process.env.TIMEOUT || 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  neo4j_data:
  neo4j_logs:
  qdrant_data:
  ollama_data:

networks:
  default:
    driver: bridge